version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - mynet

  service1:
    build: ./service_1
    container_name: service1
    expose:
      - "8001"
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  service2:
    build: ./service_2
    container_name: service2
    expose:
      - "8002"
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  mynet:
    driver: bridge

